---
title: " "
subtitle: " "
output: html_document
---

<style type="text/css">
  body{
  text-align: justify;
  text-justify: inter-word;
}
</style>

```{r,echo=FALSE,results='hide',message=FALSE, warning=FALSE}
library(DT)
library(here)
#library(googlesheets4)
library(tidyverse)
library(magrittr)

source("scripts/format-tables.R")
```


```{r,echo=FALSE,results='hide',message=FALSE, warning=FALSE}
# read in the google sheet
## set blank cells and "NA" strings to be NAs

#courses_sheet <- read_sheet("https://docs.google.com/spreadsheets/d/1TiNdu92hK-0FN8GbmWi_QbdUaX2yJF76yFt2oljm_qE/edit?usp=sharing", na = c("NA", ""))

courses_sheet <- read_csv(here("resources/CourseTable.csv"), na = c("NA", ""))

# grab just best practices courses
courses_bestpractice <- courses_sheet %>% filter(Category == "Best Practices")

bestpractices_table <- setup_table(prep_table(as_tibble(courses_bestpractice), current=TRUE), "Best Practices Courses Currently Available", columnDefsListOfLists = 
                                                          list(list(className = 'dt-center', targets = c(0,1,2)),
                                                               list(className = "dt-left", targets = c(3,4)),
                                                               list(width = '240px', targets = c(3)) ,
                                                               list(width = '160px', targets = c(4))
                                                              )
                                   )
```

<div style = "width:100%; height:auto; margin: 0; padding:10px">

```{r,echo=FALSE,message=FALSE,warning=FALSE}
#Display best practices table
bestpractices_table
```

</div>
